---
- name: Allow IP forwarding
  shell: grep 'net.ipv4.ip_forward' /etc/sysctl.conf && sed -i  's#net\.ipv4\.ip_forward.*#net\.ipv4\.ip_forward = 1#' /etc/sysctl.conf || echo 'net.ipv4.ip_forward = 1' >> /etc/sysctl.conf

- name: Install the bridge
  command: modprobe br_netfilter

- name: Enable iptables to handle bridge packets
  command: echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables

- template:
    src: ../templates/iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0644