---
- name: Allow IP forwarding
  become: true
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^net.ipv4.ip_forward=.*'
    line: 'net.ipv4.ip_forward = 1'

- name: Install the bridge
  become: true
  command: modprobe br_netfilter

- name: Enable iptables to handle bridge packets
  become: true
  command: echo "1" > /proc/sys/net/bridge/bridge-nf-call-iptables

- name: Copy the templated iptables file
  become: true
  template:
    src: ../templates/iptables.j2
    dest: /etc/sysconfig/iptables
    owner: root
    group: root
    mode: 0644